#!/bin/bash
function getuserchoice ()
{
    echo "Make a choice [1,2,3]:"         <------this shows the user a prompt
    read userchoice
    case $userchoice in                   <------ a comparison of instances
        (1) echo one ;;
        (2) echo two ;;
        (3) echo three
        (*) echo other ;;
    esac                                  <------ close case statement with "esac"
}

getuserchoice



echo /home/student | md5sum          <-------- turns the name of a directory to the md5 hash


eho $$  <---------- PID of the shell
echo $0 <--------- Name of script

if [[ $# -lt 3 ]]; then
echo "usage: bash $0 arg1 arg2 arg3";
else
echo $1 $2 $3
fi



LOOPS: WHILE, FOR, UNTIL

WHILE        <------- While the statement is true continue the loop. Stop the loop when it is false
#!/bin/bash
while [ what test ]
do
    commands
done


FOR         <------- for every item in the list apply the command to it
#!/bin/bash
for variable in list
do
    commands
done


UNTIL       <------- Execute the command until the result is true
#!/bin/bash
until test
do
    commands
done
